### ISSUE TITLE
Dev tools container

### ISSUE THREAD

**Issue by davenuman** [CivicActions/bowline#1]
Create an additional docker container with Drupal focussed developer tools:
- xDebug, Xhprof
- Ruby, Sass, Compass
- phpmyadmin
- others?

**Comment by kostajh** [comment]
+1 for XDebug.This is a blocker for some of my colleagues.

**Comment by davenuman** [comment]
The davenuman/bowline-web-php:latest image now has xdebug.

**Comment by kostajh** [comment]
:+1: thanks @davenuman!

**Comment by algeronwaterschoot** [comment]
I'm struggling to get xdebug configured in PHPStorm when working with Bowline projects. As I understand it, the Docker containers are not directly accessible via SSH, so setting up a remote interpreter via SSH is not viable. The only remaining option is to set up a remote Vagrant interpreter, but PHPStorm displays a "failed to send channel request" error. https://i.imgur.com/ZYvsdzZ.png

Any advice on what I might be doing wrong?

**Comment by grugnog** [comment]
Closing old v1 issues
