### ISSUE TITLE
504 Gateway Time-out with reverse proxy

### ISSUE THREAD

**Issue by kostajh** [CivicActions/bowline#19]
On slower moving Drupal sites, I sometimes get 504 gateway timeouts with the reverse proxy. I wonder if there is an Nginx setting we can adjust to allow more time to elapse before returning the 504.

**Comment by davenuman** [comment]
I'm reviewing this page (search for _timeout):
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

I'm not sure which one(s) to increase. I think increasing proxy_read_timeout might be the right one. Haven't had a chance to test yet.

**Comment by rmarscher** [comment]
Here are some nginx settings I typically use when reverse proxying nginx for node.js projects. I tested them with bowline and they work. `proxy_read_timeout` is probably the main one to set. Not sure if 90 seconds is enough time -- maybe certain Drupal actions need even more. You could jump it way up to 900s to give a lot of room.

```
proxy_set_header   Host             $host;
proxy_set_header   X-Real-IP        $remote_addr;
proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

client_max_body_size       10m;
client_body_buffer_size    128k;

proxy_connect_timeout      90s;
proxy_send_timeout         90s;
proxy_read_timeout         90s;

proxy_buffer_size          4k;
proxy_buffers              4 32k;
proxy_busy_buffers_size    64k;
proxy_temp_file_write_size 64k;
```

Here is the whole nginx.conf with these changes for context:

```

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    # Proxy the subdomains to docker subnet domains.
    # For sandbox usage, an example would be projectname.vcap.me  or  projectname.lvh.me
    server {
        listen       80;
        server_name  ~^(?<sub>.+)\.(.*)\.(.*)$;

        location / {
            # Use subnet DNS:
            resolver dnsmasq;
            proxy_pass http://$sub;

            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

            client_max_body_size       10m;
            client_body_buffer_size    128k;

            proxy_connect_timeout      90s;
            proxy_send_timeout         90s;
            proxy_read_timeout         90s;

            proxy_buffer_size          4k;
            proxy_buffers              4 32k;
            proxy_busy_buffers_size    64k;
            proxy_temp_file_write_size 64k;
       }
    }
}
```

**Comment by gabeno** [comment]
Note: ```proxy_connect_timeout      90s;``` can be set at max ```75s``` see [here](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout)

**Comment by flybyray** [comment]
and why? ok it is a note but is there a reason?

**Comment by calamarico** [comment]
I had a 10 min timeout in my express server, and without any proxy parameter in Ubuntu 16.04 there wasn't any problem, but in CentOS and Redhat there was a 1 min restriction, and adding proxy params run ok.
So, I think nginx by default, is taking an operative system configuration about timeout.

**Comment by grugnog** [comment]
Closing old v1 issues
