### ISSUE TITLE
PHP 5.3/5.4 strategy

### ISSUE THREAD

**Issue by kostajh** [CivicActions/bowline#26]
Hi @davenuman,

I noticed you have php-5.3 and php-5.4 branches, but they seem pretty far behind `master`. I'm wondering if you think there is a way that one could specify to use php 5.3/5.4 in a config file, and have all the code live in the `master` branch.

**Comment by ducdebreme** [comment]
First my compliments for sharing this execellent project :-)
Yes @davenuman , I am also wondering what your idea is about having different php versions at head. php 5.5 might nowadays also a good thing.

**Comment by davenuman** [comment]
Agreed, php 5.5 is needed now. My current thinking is to completely decouple the docker image from the bowline project. I started working on a centos 7 based image with 5.5: https://github.com/davenuman/docker-bowline

The way I see it, Bowline is more about the bash scripts than the image and I'd like to see the freedom to more easily select the appropriate image for each drupal project. Once I have a solid set up for using different images I'll probably remove the Dockerfile builds in this repo. That would solve the 5.3/5.4 branch problem but would also be a cleaner codebase.

**Comment by ducdebreme** [comment]
Thanks for the clarification. I completely agree: Bowline should contain the script files and the Dockerfiles should be kept in a different location.

I like your approach to use official images such as the mysql images, which offers the flexibility to easily change versions. Don't you think, we could also use a "standard" php image such as https://registry.hub.docker.com/_/php/ or similar?

**Comment by kostajh** [comment]
> My current thinking is to completely decouple the docker image from the bowline project.
:+1: 
@davenuman any update on progress with this?

**Comment by martinfrances107** [comment]
From the opening issue 

> I noticed you have php-5.3 and php-5.4 branches, but they seem pretty far behind master

From over a year ago - so that statement needs emphasis.

For Drupal8 development. I think the true perspective is as follow:

Given the moderate performance boost and massive memory reduction that php7 brings 
I think we should consider adding that as an option. Core will change its minimum requirements slowly
but for any new site there is no good reason not to use PHP7.

**Comment by grugnog** [comment]
Closing old v1 issues
