### ISSUE TITLE
Another drupal docker container

### ISSUE THREAD

**Issue by Boran** [CivicActions/bowline#3]
Hi, Just cam across your project, interesting.. I also created a Drupal docker image, with lots of flexibility.
Now may aim was a bit different: Allow automated creation of simple websites in minutes.
see https://github.com/Boran/docker-drupal
"Install Ubuntu 14.04/Apache/Mysql with supervisord startup scripts
Install composer and drush
Use included Drupal7, or download Drupal, pull from git or via drush makefile
Install drupal+DB via a standard or custom profile. DB within or outside the container.
Most drupal install settings are environment settings when creating a container from the image."

Its more of a lightweight VM than a single process container.
For CI: created containers for jenkins, and a build container for jenkins (docker-drupal, docker-cibuild on my github account).
Finally a UI for managing docker and specifically containers build with these images (called webfactory, hope to have an operation version on github in the next 10 days)

It might be interesting to cross pollinate or discuss concepts...

**Comment by davenuman** [comment]
@Boran thanks for sharing. That is a very robust looking docker image you've built. I already use Bowline with different web containers and could imagine these two project could work well together. I hope to get a chance soon to try plugging your image into my fig configuration. Interested in cross-pollinating.

**Comment by grugnog** [comment]
Closing old v1 issues
