### ISSUE TITLE
Add note to documentation, drupal code needs to be in docroot folder

### ISSUE THREAD

**Issue by rmarscher** [CivicActions/bowline#30]
First off, this project is awesome. Thank you.

I think it isn't obvious from the "existing project" section of the readme that the drupal code needs to be placed in a subfolder called docroot. Those instructions won't work with projects that have the drupal code in the root folder of the git repo.

I used bowline to get a local dev environment from a project hosted on pantheon.io. With Pantheon, the git repo has the drupal files in the root of the project. A git submodule might be the appropriate way to add it. I ended up just using bowline as-is and cloning the pantheon repo into the docroot folder. That seems to work fine.

```
git clone https://github.com/davenuman/bowline.git
cd bowline
# ... downloaded a db export from Pantheon and renamed it to .snapshot.sql.gz inside the bowline dir
git clone ssh://codeserver.{PANTHEON-ENV}.{PANTHEON-SITE-UUID}@codeserver.{PANTHEON-ENV}.{PANTHEON-SITE-UUID}.drush.in:2222/~/repository.git docroot
rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222' {PANTHEON-ENV}.{PANTHEON-SITE-UUID}@appserver.{PANTHEON-ENV}.{PANTHEON-SITE-UUID}.drush.in:files/ docroot/sites/default/files
. bin/activate
build
settings_init
import
drush st
```

**Comment by kostajh** [comment]
I would love to remove the dependency on a directory named "docroot". Could we use a configuration file (or script) to allow the user to specify where in the repo the Drupal root is, and go from there?

**Comment by davenuman** [comment]
@kostajh I've been starting to thinkg about improvements to bowline lately and some minimal config might really help. Thanks.  I'd like to create more separation between the bowline docker images and the bowline project itself, allowing people to mess with the docker-compose.yml file easier. A configurable docroot would help that along.

**Comment by kostajh** [comment]
@davenuman I'd love to help. It would be great to be able to override the images used (for PHP version, or to install additional software like Solr). Let me know what I can do.

David H Numan writes:

> @kostajh I've been starting to thinkg about improvements to bowline lately and some minimal config might really help. Thanks.  I'd like to create more separation between the bowline docker images and the bowline project itself, allowing people to mess with the docker-compose.yml file easier. A configurable docroot would help that along.  
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/davenuman/bowline/issues/30#issuecomment-189999984


-- 
@kostajh | kosta@kostaharlan.net

**Comment by grugnog** [comment]
Closing old v1 issues
