### ISSUE TITLE
dev tools container - compass error

### ISSUE THREAD

**Issue by evilp** [CivicActions/bowline#34]
Cool Project! 
But there is a problem when i try to run compass or compass-watch. Error: compass not found in $PATH.

I installed the devtools with hoist, like recommended.

Rest works fine.

**Comment by davenuman** [comment]
Sorry to say the devtools is still a work-in-progress. We're not using it on our current projects but I hope to get it working soon for  next up projects.

**Comment by grugnog** [comment]
Closing old v1 issues
