### ISSUE TITLE
After stopping the containers, they do not start anymore

### ISSUE THREAD

**Issue by ducdebreme** [CivicActions/bowline#40]
When I build my containers, install D8 and do a restart of the containers, they don't come back.

Error message:
**Cannot restart container 72cb6d0e6ecabbabf6ea07c57aec8192fefd7109e3b2ef73a02f856138c248b6: Cannot link to a non running container: /bowlinedrupal8_php_1 AS /bowlinedrupal8_web_1/bowlinedrupal8_php_1**

It turns out that **bowlinedrupal8_php_1** is the bad guy. You can not event start it using 

```
docker start bowlinedrupal8_php_1
```

This is, what I did

```
$ build
# STARTING CONTAINERS
Creating bowlinedrupal8_db_1...
Creating bowlinedrupal8_php_1...
Creating bowlinedrupal8_web_1...
 Exit Status: 0
Available commands:  deactivate
activate  bowline  check     destroy  enter  hoist   invoke_proxy  phpcs  settings_init
backup    build    composer  drush    fix-perms  import  phpcbf        run

Containers: 
db   ~  172.17.0.36
php  ~  172.17.0.37
web  ~  172.17.0.38  http://172.17.0.38/
Proxy:
  Not active. (use 'invoke_proxy' to start)

$ (bowline_drupal8) $ settings_init
Docker settings file already initialized.
Hint: If you would like to perform a fresh site install, run this:
  drush si --sites-subdir=default

$ (bowline_drupal8) $ drush si --sites-subdir=default
Running 'drush si --sites-subdir=default' inside container, using uri: http://172.17.0.38/
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global              [ok]
option.
Installation complete.  User name: admin  User password: 8aWLJ5kLDM                               [ok]
Congratulations, you installed Drupal!                                                        [status]

$ (bowline_drupal8) $ docker-compose restart
Restarting bowlinedrupal8_db_1...
Restarting bowlinedrupal8_php_1...
Restarting bowlinedrupal8_web_1...
Cannot restart container 72cb6d0e6ecabbabf6ea07c57aec8192fefd7109e3b2ef73a02f856138c248b6: Cannot link to a non running container: /bowlinedrupal8_php_1 AS /bowlinedrupal8_web_1/bowlinedrupal8_php_1
```

**Comment by MrTB** [comment]
same issue by me:

>`$ build`
>\# STARTING CONTAINERS
>Starting drupal8_db_1
>Starting drupal8_php_1
>Starting drupal8_web_1
> Exit Status: 0
>Available commands:  deactivate
>activate	bowline		check		destroy		enter		hoist		invoke_proxy	>phpcs		settings_init
>backup		build		composer	drush		fix-perms	import		phpcbf		run		stop
>
>Containers:
>db   ~  172.17.0.2
>php  ~  not running
>web  ~  not running
>Proxy:
>	Not active. (use 'invoke_proxy' to start)

**Comment by MrTB** [comment]
Hi, it help me to use the 
`docker-compose rm `
to start the containers again.

I hope it help you too @ducdebreme

**Comment by grugnog** [comment]
Closing old v1 issues
