### ISSUE TITLE
Proxy nginx doesn't start

### ISSUE THREAD

**Issue by grugnog** [CivicActions/bowline#41]
I get an error like:
`ERROR: b'Cannot start container 4ba007769bfc573b85db7599882dc435407e7cd792140910f536f88fb1b81e34: [8] System error: not a directory'`

I was able to resolve with the following change:

```
diff --git a/lib/proxy/fig.yml b/lib/proxy/fig.yml
index 1bfda8b..19fac2c 100644
--- a/lib/proxy/fig.yml
+++ b/lib/proxy/fig.yml
@@ -1,10 +1,8 @@
 dnsmasq:
   build: dnsmasq
 nginx:
-  image: nginx
+  build: nginx
   ports:
     - 80:80
-  volumes:
-    - nginx.conf:/etc/nginx/nginx.conf:ro
   links:
     - dnsmasq:dnsmasq
diff --git a/lib/proxy/nginx/Dockerfile b/lib/proxy/nginx/Dockerfile
new file mode 100644
index 0000000..01bad77
--- /dev/null
+++ b/lib/proxy/nginx/Dockerfile
@@ -0,0 +1,2 @@
+FROM nginx
+COPY nginx.conf /etc/nginx/nginx.conf
diff --git a/lib/proxy/nginx.conf b/lib/proxy/nginx/nginx.conf
similarity index 100%
rename from lib/proxy/nginx.conf
rename to lib/proxy/nginx/nginx.conf
```

**Comment by curveadmin** [comment]
Same issue, when I visit http://$project.localtest.me it just serves my locally installed apache sites.

Did you manage to fix this?

**Comment by kostajh** [comment]
I'm seeing the same problem with the proxy not starting, haven't tested this patch yet.

**Comment by davenuman** [comment]
I like the patch however the [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) has a good reputation and might be better than trying to recreate such a proxy here. i'll see if I can cleanly make use of it.

**Comment by davenuman** [comment]
update: I'm now working with and testing the traefik proxy. So far so good.

**Comment by grugnog** [comment]
Closing old v1 issues
