### ISSUE TITLE
Move this project's directories into a single one

### ISSUE THREAD

**Issue by kostajh** [CivicActions/bowline#43]
Just a proposal to help keep repo structure clean:
- (a) consolidate everything (`bin`, `lib`, `.docker`) into a single `.bowline` or `.docker` directory
- (b) keep `bin` but move `lib` into `.docker`

**Comment by openprivacy** [comment]
I like this. Having everything in `.bowline` (one place) and using `source .bowline/activate` to (among other things) add `.bowline/bin` to `$PATH` would simplify upgrading bowline and keep the repository clean. And there would be just one place for all bowline files.

**Comment by davenuman** [comment]
I like this too. Going with `.bowline` for example, it would also be a good spot for storing config as mentioned on another issue. (https://github.com/davenuman/bowline/issues/30#issuecomment-189955530)  Perhaps `.bowline/config/env` for setting environment veriables used by bowline.
