### ISSUE TITLE
Ability for custom hoist riggings

### ISSUE THREAD

**Issue by kostajh** [CivicActions/bowline#45]
Folks will probably have a need for creating custom hoist riggings that don't need to be merged upstream. Could we have a dedicated directory that bowline can search for custom hoists? related: #43

**Comment by davenuman** [comment]
I believe 38520f8 achieves what we want here. One can add riggings to any path on their system with riggings external to the bowline repo. The path could also be a set of riggings tacked by another git repo.

Not closing this issue yet as this still needs to be documented in the readme.

**Comment by davenuman** [comment]
Quick how-to example that needs to be documented yet:

```
cp .bowline/config.example .bowline/config
mkdir -p ~/bowline/riggings/foo

cat << EOF > ~/bowline/riggings/foo/foo.hoist
#!/usr/bin/env bash
echo "# Installing foo bar"
EOF

hoist
```

**Comment by davenuman** [comment]
the output of that would be this:

```
 » hoist
Usage: hoist [rigging]

Available Bowline riggings:
behat  codeception  devtools  drupal-core-dev  phpunit

Available local riggings (in /home/dave/bowline/riggings):
foo

Note: if there are name conflicts, the local riggings will be used.
```

```
 » hoist foo
# Installing foo bar
```
