### ISSUE TITLE
The one command for installation given in the read me did not work

### ISSUE THREAD

**Issue by fmizzell** [CivicActions/bowline#46]
I am in ubuntu, using z shell, and the command simply got the install script (the wget section) but was not able to execute the rest. 

I am not sure what the issue is. Probaby z shell. Would it be worth it to add extra instruction in case of failure? Something like:
`chmod 777 bowline-install.sh
./bowline-install.sh
`

**Comment by grugnog** [comment]
Closing old v1 issues
